import type { Packet } from '../review/packet';
import type { View, Source } from './model';
import type { BundleResponse, EvidenceResponse, PathLink } from '../tokenomics/api';
import type { GraphAnswer } from './graph';
import { answerQuestion } from './tokenomics-questions';
import { bonkStory, mndeStory, units, answerBonk, type WalkthroughFact } from './case-walkthrough-model';

const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const short=(s:string|null|undefined)=>s?`${s.slice(0,6)}…${s.slice(-4)}`:'Not established';
const date=(s:string|null|undefined)=>s?new Date(s).toISOString().slice(0,16).replace('T',' ')+' UTC':'Date not established';
const fetchJson=async<T>(url:string):Promise<T>=>{const r=await fetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`Evidence API returned ${r.status}. Keep the completed workspace available.`);return r.json();};
let caseId:'bonk'|'mnde'='bonk',scene=0,request=0,sourceRequest=0;
let packet:Packet|null=null,view:View|null=null,bundle:BundleResponse|null=null,graph:GraphAnswer|null=null;
let error='',selectedFact:WalkthroughFact|null=null,messages:{q:string;facts:WalkthroughFact[];text:string}[]=[];
const root=document.createElement('section');root.id='case-walkthrough';root.hidden=true;root.setAttribute('aria-label','Guided case walkthrough');document.body.append(root);
const launcher=document.createElement('button');launcher.id='case-walkthrough-launch';launcher.textContent='Guided walkthrough ↗';launcher.onclick=()=>location.hash='walkthrough-bonk';document.body.append(launcher);
const steps=()=>caseId==='bonk'?['The proposal','How it passed','What executed','Cited memo']:['The value path','Who controls it','What we observed','Cited memo'];
const currentFacts=():WalkthroughFact[]=>caseId==='bonk'&&packet?bonkStory(packet).facts:bundle?mndeStory(bundle).facts:[];
function factButton(f:WalkthroughFact,label='Inspect evidence ↗'){const i=currentFacts().findIndex(x=>x.label===f.label);return `<button class="walkthrough-text" data-walkthrough-fact="${i}">${esc(label)}</button>`;}
function linkButton(id:string,label:string){return `<button class="walkthrough-link" data-walkthrough-link="${esc(id)}">${esc(label)} ↗</button>`;}
function metric(value:string,label:string,note:string){return `<div class="walkthrough-metric"><strong>${esc(value)}</strong><span>${esc(label)}</span><small>${esc(note)}</small></div>`;}
function node(label:string,sub:string,action:string){return `<button class="walkthrough-node" ${action}><strong>${esc(label)}</strong><small>${esc(sub)}</small></button>`;}
function arrow(label:string,kind='verified',action=''){return `<div class="walkthrough-arrow ${kind}"><span>${esc(label)}</span><button ${action} aria-label="Inspect ${esc(label)}">→</button></div>`;}
function render(){
  const loaded=caseId==='bonk'?!!packet:!!bundle;
  root.innerHTML=`<header class="walkthrough-top"><a class="walkthrough-brand" href="/#${caseId==='bonk'?'bonk-bip76':'tokenomics'}" data-walkthrough-exit>linchpin <span>GUIDED WALKTHROUGH</span></a><nav aria-label="Walkthrough cases"><button data-walkthrough-case="bonk" aria-pressed="${caseId==='bonk'}">01 · BonkDAO</button><button data-walkthrough-case="mnde" aria-pressed="${caseId==='mnde'}">02 · Marinade / MNDE</button></nav><button class="walkthrough-secondary" data-walkthrough-reload>Reload stored evidence ↻</button><a class="walkthrough-text" href="/#${caseId==='bonk'?'bonk-bip76':'tokenomics'}" data-walkthrough-exit>Open full workspace ↗</a></header>
  <div class="walkthrough-layout"><main class="walkthrough-main"><div class="walkthrough-kicker">${caseId==='bonk'?'GOVERNANCE REVIEW · HISTORICAL CASE':'PROTOCOL RESEARCH · TOKENOMICS'}</div><h1>${caseId==='bonk'?'A vote. A transfer. Almost nothing left.':'Does protocol activity reach MNDE holders?'}</h1><p class="walkthrough-deck">${caseId==='bonk'?'BIP-76 connected proposal intent, governance authority and a treasury transfer. Here is what the recorded evidence establishes.':'Follow the money, distinguish code from account operations, and find who can change the route.'}</p>
  <nav class="walkthrough-scenes" aria-label="Walkthrough steps">${steps().map((s,i)=>`<button data-walkthrough-scene="${i}" aria-current="${scene===i?'step':'false'}"><span>${i+1}</span>${esc(s)}</button>`).join('')}</nav>
  <section id="walkthrough-stage" tabindex="-1">${error?`<div class="walkthrough-error" role="alert">${esc(error)}<button data-walkthrough-reload>Retry</button></div>`:loaded?(caseId==='bonk'?renderBonk():renderMnde()):'<p class="walkthrough-loading" role="status">Retrieving the case and its graph evidence…</p>'}</section>
  <footer class="walkthrough-foot"><span>${caseId==='bonk'?'Retrospective reconstruction · one BONK source account':'Recorded mainnet state + historical flow windows'}</span><div><button class="walkthrough-secondary" data-walkthrough-previous ${scene===0?'disabled':''}>← Previous</button><button class="walkthrough-primary" data-walkthrough-next>${scene===3?(caseId==='bonk'?'Next case: MNDE →':'Restart cases ↻'):'Next →'}</button></div></footer></main>
  <aside class="walkthrough-rail" aria-label="Questions and evidence"><h2>Ask the evidence</h2><p class="walkthrough-muted">Questions retrieve cited records. No live language model is used.</p><div class="walkthrough-prompts">${(caseId==='bonk'?['Was the transfer hidden?','How did the vote pass?','What did the receipt prove?']:['Who can change the fees?','Are all credits purchases?','Is the 10% allocation verified?']).map(q=>`<button data-walkthrough-question="${esc(q)}" ${loaded?'':'disabled'}>${esc(q)} ↗</button>`).join('')}</div><div id="walkthrough-conversation" aria-live="polite">${chatHtml()}</div><form id="walkthrough-question-form"><label for="walkthrough-question">Question about this case</label><div><input id="walkthrough-question" name="question" placeholder="${caseId==='bonk'?'Ask about the transfer or vote…':'Ask about fees, controls or flows…'}" maxlength="500" ${loaded?'':'disabled'} required><button class="walkthrough-primary" type="submit" ${loaded?'':'disabled'}>Ask</button></div></form><section id="walkthrough-evidence"><h3>Evidence inspector</h3><p class="walkthrough-muted">Click a diagram node, route or citation to see its basis, date and supporting records.</p></section></aside></div>`;
  root.querySelector('#walkthrough-question-form')?.addEventListener('submit',e=>{e.preventDefault();const q=(root.querySelector('#walkthrough-question') as HTMLInputElement).value.trim();if(q)ask(q);});
}
function renderBonk(){const p=packet!,s=bonkStory(p);
  const badge=graph?graph.source==='neo4j'?`Neo4j Aura · ${graph.host}`:`Local graph · ${graph.reason??'offline fallback'}`:'Graph query pending';
  const inventory=graph?.queries.find(q=>q.id==='case-inventory')?.rows.find(r=>r.case==='bonk-bip76');
  const state=`<p class="walkthrough-provenance">Captured ${date(view?.capturedRange[0])} · ${p.evidenceCount} evidence records · <button class="walkthrough-text" data-walkthrough-graph>${esc(badge)} ↗</button>${inventory?` · ${inventory.nodes} case nodes / ${inventory.relationships} relations`:''}</p>`;
  if(scene===0)return `${state}<div class="walkthrough-scene-title"><h2>${s.matched?`${(Number(s.transfer.amountRaw)/10**s.transfer.decimals!/1e12).toFixed(3)} trillion BONK moved.`:`A ${(Number(s.transfer.amountRaw)/10**s.transfer.decimals!/1e12).toFixed(3)} trillion BONK transfer was decoded.`}</h2><span class="walkthrough-basis">${s.matched?'RECEIPT MATCHED':'DECODED ONLY'}</span></div><p>The proposal text explicitly requested the transfer. The important connection is the declared action → the authority → the executed effect.</p><div class="walkthrough-flow">${node('BONK treasury account',short(s.transfer.source),'data-walkthrough-fact="1"')}${arrow('Transfer', 'verified','data-walkthrough-fact="1"')}${node('New receiving account',short(s.transfer.destination),'data-walkthrough-fact="2"')}${arrow('Owned by','verified','data-walkthrough-fact="0"')}${node('Recipient wallet',short(s.creationOwner),'data-walkthrough-fact="0"')}</div><div class="walkthrough-amount"><strong>${esc(s.amount)}</strong><span>BONK · decoded payload${s.matched?' and matched execution receipt':''}</span>${factButton(s.facts[2]!)}</div><div class="walkthrough-callout"><strong>Intent is visible in the proposal.</strong><p>${esc(p.claimed.find(c=>c.id==='c2')?.text??'Claim unavailable')}</p>${factButton(s.facts[0]!)}</div>`;
  if(scene===1){const share=Number(s.approveShare??0),threshold=s.threshold;const zoom=threshold!=null&&Math.abs(share-threshold)<0.1;const lo=zoom?threshold!-0.02:0,hi=zoom?threshold!+0.02:Math.max(100,share,threshold??0);const x=(v:number)=>Math.max(0,Math.min(100,(v-lo)/(hi-lo)*100));return `${state}<div class="walkthrough-scene-title"><h2>A narrow margin. A fast execution.</h2><span class="walkthrough-basis">DECODED + OBSERVED</span></div><div class="walkthrough-metrics">${metric(`${s.approveShare??'Unknown'}%`,'Approval / maximum vote weight','Uses the proposal’s recorded denominator')}${metric(`${s.threshold??'Unknown'}%`,'Stored approval threshold','Not the percentage of participating voters')}${metric(`${p.governance.minInstructionHoldUpTime} s`,'Captured governance hold-up','Governance state captured in October')}</div><div class="walkthrough-vote"><h3>Approval against threshold</h3><p>${zoom?'Zoomed scale: '+lo.toFixed(2)+'–'+hi.toFixed(2)+'%':'Scale: '+lo+'–'+hi+'%'} of maximum vote weight</p><div class="walkthrough-vote-track"><div style="width:${x(share)}%"></div>${threshold==null?'':`<span class="walkthrough-threshold" style="left:${x(threshold)}%"><b>${threshold}% threshold</b></span>`}</div><div class="walkthrough-vote-axis"><span>${lo.toFixed(2)}%</span><strong>${s.approveShare}% approval</strong><span>${hi.toFixed(2)}%</span></div></div><div class="walkthrough-callout"><strong>Execution began at +${s.firstDelay??'?'} seconds; the transfer completed at +${s.transferDelay??'?'} seconds.</strong><p>These are receipt timestamps relative to voting completion. Voter concentration and vote buying remain reported claims, outside this reconstruction.</p>${factButton(s.facts[3]!)}</div>`;}
  if(scene===2)return `${state}<div class="walkthrough-scene-title"><h2>${s.matched?'The receipt closes the loop.':'Receipt reconciliation remains unresolved.'}</h2><span class="walkthrough-basis">OBSERVED EXECUTION</span></div><div class="walkthrough-receipts">${p.decoded.map((d,i)=>{const r=p.observed.receipts.find(r=>r.txIndex===i);return `<button data-walkthrough-receipt="${i}"><span>Transaction ${i+1}</span><strong>${d.kind==='unsupported'?'Metadata · unresolved':d.kind==='createAccount'?'Create receiving account':'Transfer BONK'}</strong><small>${r?.blockTime&&p.proposal.votingCompletedAt!=null?'+'+(r.blockTime-p.proposal.votingCompletedAt)+' s':'Time unavailable'} · ${r?.success?'receipt success':'not established'}</small></button>`;}).join('')}</div><div class="walkthrough-balances"><div><span>Source before execution</span><strong>${esc(s.sourceBefore??'Unknown')}</strong><small>BONK · receipt pre-balance</small></div><b>→</b><div><span>Source after execution</span><strong>${esc(s.remaining??'Unknown')}</strong><small>BONK · receipt post-balance</small></div></div><p class="walkthrough-callout"><strong>${s.share==='99.9999'?'>99.9999%':esc(s.share??'Unknown')+'%'} of this account’s BONK transferred.</strong> The exact raw balance, rather than today’s balance, is the denominator. ${s.matched?'Decoded and observed deltas match.':'A matched delta is not established.'}</p><p class="walkthrough-muted">${s.receipt?`${date(s.receipt.blockTime?new Date(s.receipt.blockTime*1000).toISOString():null)} · slot ${s.receipt.slot} · receipt ${short(s.receipt.signature)}`:'Historical receipt unavailable'}. Two metadata payloads remain unsupported; success does not establish their meaning.</p>${factButton(s.facts[2]!)}`;
  return `${state}<div class="walkthrough-scene-title"><h2>A review you can inspect and export.</h2><span class="walkthrough-basis">DRAFT · HUMAN REVIEW</span></div>${memoHtml()}<div class="walkthrough-export"><a class="walkthrough-primary" href="/api/walkthrough/${caseId}/memo.md" download>Download cited memo ↓</a><a class="walkthrough-secondary" href="/api/cases/bonk-bip76/export/packet.json">Full proposal packet ↓</a></div>`;
}
function pathRow(ids:string[]){const b=bundle!,s=mndeStory(b);return `<div class="walkthrough-path-row">${ids.map((id,i)=>{const l=s.get(id);if(!l)return '<span>Route unavailable</span>';const from=b.path.data?.nodes.find(n=>n.id===l.from),to=b.path.data?.nodes.find(n=>n.id===l.to);return `${i===0?node(from?.id==='mnde-purchases'?'MNDE credits & purchases':from?.label??l.from,from?.address?short(from.address):'Recorded mechanism',`data-walkthrough-link="${esc(id)}"`):''}${arrow(l.status==='enforced-by-code'?'Code route':l.status==='claimed-only'?'Claimed link':l.status==='pending'?'Unresolved':'Account operation',l.status==='enforced-by-code'?'verified':l.status==='claimed-only'||l.status==='pending'?'claimed':'operated',`data-walkthrough-link="${esc(id)}"`)}${node(to?.id==='mnde-purchases'?'MNDE credits & purchases':to?.label??l.to,to?.address?short(to.address):l.status.replaceAll('-',' '),`data-walkthrough-link="${esc(id)}"`)}`;}).join('')}</div>`;}
function renderMnde(){const b=bundle!,s=mndeStory(b),g=b.graph.data;const state=`<p class="walkthrough-provenance">Fee state ${date(s.lp?.asOf)} · <button class="walkthrough-text" data-walkthrough-graph>${esc(g?.source==='neo4j'?`Neo4j Aura · ${g.host}`:`Local graph · ${g?.reason??'offline fallback'}`)} ↗</button></p>`;
  if(scene===0)return `${state}<div class="walkthrough-scene-title"><h2>Partly enforced. Follow each link.</h2><span class="walkthrough-basis">CLAIM → CODE → DATA</span></div><p>Program fees reach the treasury. Revenue allocation, buybacks and distributor funding depend on additional evidence and account operations.</p><div class="walkthrough-paths">${pathRow(['liquid-lp-fee','lp-treasury'])}${pathRow(['treasury-onward','revenue-buyback'])}${pathRow(['buyback-purchases','purchases-stakers'])}</div><div class="walkthrough-legend"><span class="verified">━━ Enforced by code</span><span class="operated">┄ Account operations</span><span class="claimed">┄ Claimed / unresolved</span></div><div class="walkthrough-callout"><strong>The 10% revenue allocation is unresolved.</strong><p>Different sample windows and a missing revenue denominator prevent a verified ratio. The lower row shows observed operations; it does not prove those exact purchased tokens reached eligible holders.</p>${linkButton('revenue-buyback','Inspect the missing link')}</div>`;
  if(scene===1)return `${state}<div class="walkthrough-scene-title"><h2>Fee control and holder voting are separate.</h2><span class="walkthrough-basis">DECLARED + DECODED</span></div><div class="walkthrough-control-lanes"><h3>Who sets the fee route?</h3>${pathRow(['council-admin','admin-fees'])}<h3>Where do MNDE holders vote?</h3>${pathRow(['vote-treasury','governance-treasury'])}</div><div class="walkthrough-metrics">${metric(s.lp?.display??'Unknown','Treasury cut of the LP fee','Not 50% of deposits or all revenue')}${metric(s.withdraw?.display??'Unknown','Stake-account withdrawal fee','Decoded parameter')}${metric(s.reward?.display??'Unknown','Reward fee','Decoded parameter')}</div><p class="walkthrough-callout"><strong>${esc(s.council?.label??'Council unresolved')}</strong> controls fee settings through council-only admin governance. MNDE community voting applies to a distinct DAO treasury governance. ${linkButton('council-admin','Inspect voting rules')}</p>`;
  if(scene===2){const claims=s.claims?.observed,buys=s.buys?.observed;return `${state}<div class="walkthrough-scene-title"><h2>Observed flows with precise limits.</h2><span class="walkthrough-basis">HISTORICAL DATA</span></div><div class="walkthrough-flow-total"><span>MNDE received by the listed buyback wallet</span><strong>${esc(buys?.amount.display??'Not established')} <small>MNDE</small></strong><p>${buys?buys.window.map(x=>x.slice(0,10)).join(' → '):'Window unavailable'} · receipts are not all purchases</p></div><div class="walkthrough-split"><div><strong>${esc(s.paid??'Unknown')}</strong><span>MNDE · same-transaction paid purchases</span></div><div><strong>${esc(s.unpaid??'Unknown')}</strong><span>MNDE · credits without same-transaction payment</span></div></div>${linkButton('buyback-purchases','Inspect purchase classification')}<div class="walkthrough-claim-flow"><div><strong>${esc(claims?.amount.display??'Unknown')}</strong><span>MNDE claimed from the distributor vault</span><small>${claims?claims.window.map(x=>x.slice(0,10)).join(' → '):'Window unavailable'}</small></div><div><strong>${claims?.voterAuthorityClaimants??'?'} / ${claims?.distinctClaimants??'?'}</strong><span>known claimants match current VSR lockers</span><small>Current overlap; historical eligibility unverified</small></div></div><p class="walkthrough-callout">${linkButton('purchases-stakers','Inspect observed claims')} Eligibility is defined off chain. These claims do not establish a universal automatic payout to MNDE holders or trace fungible purchased tokens through the vault.</p>`;}
  return `${state}<div class="walkthrough-scene-title"><h2>A tokenomics answer with its dependencies.</h2><span class="walkthrough-basis">DRAFT · HUMAN REVIEW</span></div>${memoHtml()}<div class="walkthrough-export"><a class="walkthrough-primary" href="/api/walkthrough/${caseId}/memo.md" download>Download cited memo ↓</a><a class="walkthrough-secondary" href="/api/tokenomics/marinade/export/tokenomics.json">Full tokenomics bundle ↓</a></div>`;
}
function memoHtml(){return `<article class="walkthrough-memo">${currentFacts().map((f,i)=>`<section><h3>${esc(f.label)} <button class="walkthrough-citation" data-walkthrough-fact="${i}" aria-label="Inspect memo citation ${i+1}">[${i+1}]</button></h3><p>${esc(f.text.length>750?f.text.slice(0,750)+'…':f.text)}</p><small>${esc(f.basis)}${f.asOf?' · '+date(f.asOf):''}</small></section>`).join('')}</article>`;}
function chatHtml(){return messages.length?messages.map((m,i)=>`<div class="walkthrough-chat"><strong>${esc(m.q)}</strong><p>${esc(m.text)}</p>${m.facts.map((f,j)=>`<p>${esc(f.text)} <button class="walkthrough-citation" data-walkthrough-chat-cite="${i}:${j}" aria-label="Inspect answer citation ${j+1}">[${j+1}]</button></p>`).join('')}</div>`).join(''):'<p class="walkthrough-muted">Start with a suggested question, or click a dependency in the main view.</p>';}
function ask(q:string){if(caseId==='bonk'?!packet:!bundle)return;let facts:WalkthroughFact[]=[],text='These records support the answer.';
  if(caseId==='bonk'&&packet)facts=answerBonk(q,bonkStory(packet));
  else if(bundle){const s=mndeStory(bundle);if(/10%|allocation|ratio/.test(q.toLowerCase()))facts=s.facts.filter(f=>f.label==='10% revenue allocation');else if(/credits|purchases|bought/.test(q.toLowerCase())){const l=s.buys;if(l)facts=[{label:'Buyback classification',text:`${s.paid} MNDE in same-transaction paid purchases; ${s.unpaid} MNDE credited without payment in the same transaction. Costs of those credits are not observed in those receipts.`,basis:'observed + derived',ids:l.evidenceIds,asOf:l.asOf,slot:l.slot}];}else {const a=answerQuestion(q,bundle);text=a.text;facts=a.facts.map(f=>({label:f.id,text:f.text,basis:Array.isArray(f.basis)?f.basis.join(' + '):f.basis,ids:f.evidenceIds,asOf:f.asOf,slot:f.slot}));}}
  if(!facts.length)text='This question is not established by the captured case. Ask about its transfer, vote, fees, controls, flows or unresolved evidence.';
  messages.push({q,facts,text});render();root.querySelector('#walkthrough-conversation')?.scrollTo({top:100000,behavior:'smooth'});
}
async function inspect(f:WalkthroughFact){selectedFact=f;const n=++sourceRequest,body=root.querySelector('#walkthrough-evidence')!;body.innerHTML=`<h3>${esc(f.label)}</h3><span class="walkthrough-basis">${esc(f.basis)}</span><p>${esc(f.text)}</p><p class="walkthrough-muted">${date(f.asOf)}${f.slot!=null?' · slot '+f.slot:''}</p><p role="status">Loading supporting records…</p>`;
  try{const ids=[...new Set(f.ids)].slice(0,8);let html='';if(caseId==='bonk'){const result=await fetchJson<{items:Source[];more:boolean}>(`/api/cases/bonk-bip76/sources?${ids.map(id=>'id='+encodeURIComponent(id)).join('&')}`);html=result.items.map(s=>`<details><summary>${esc(s.title)}</summary><p>${date(s.capturedAt)} · slot ${s.slot??'n/a'}</p><code>${esc(s.id)}</code><pre>${esc(JSON.stringify(s.detail,null,2))}</pre></details>`).join('');}else {const result=await fetchJson<EvidenceResponse>(`/api/tokenomics/marinade/evidence?${ids.map(id=>'id='+encodeURIComponent(id)).join('&')}`);html=result.items.map(s=>`<details><summary>${esc(s.method)} · slot ${s.slot??'n/a'}</summary><p>${date(s.retrievedAt)} · ${esc(s.source)}</p><code>${esc(s.id)}</code><pre>${esc(JSON.stringify(s,null,2))}</pre></details>`).join('');if(result.missing.length)html+=`<p>${result.missing.length} requested records are unavailable.</p>`;}
    if(n!==sourceRequest||selectedFact!==f)return;body.querySelector('[role=status]')!.outerHTML=html||'<p>No direct supporting records attached. Treat this as unresolved.</p>';body.innerHTML+=`<p class="walkthrough-muted">${f.ids.length} attached references · first ${Math.min(8,f.ids.length)} requested. Full source set is retained in the exported memo and research packet.</p>`;
  }catch{if(n===sourceRequest)body.querySelector('[role=status]')!.textContent='Supporting records could not be retrieved. The fact remains in the stored capture.';}
}
function inspectLink(id:string){const l=bundle?.path.data?.links.find(l=>l.id===id);if(!l)return;let text=l.note;
  if(l.status==='claimed-only'&&id==='revenue-buyback')text='MIP-22 claims 10% of protocol revenue goes to buybacks. Different windows and a missing same-window revenue denominator prevent a verified allocation ratio.';
  if(l.observed)text+=` Observed ${l.observed.amount.display} ${l.observed.amount.unit}; ${l.observed.window.join(' → ')}.`;
  void inspect({label:l.mechanism,text,basis:l.status+' · '+(Array.isArray(l.basis)?l.basis.join(' + '):l.basis),ids:[...l.evidenceIds,...(l.observed?.evidenceIds??[])],asOf:l.asOf,slot:l.slot});
}
function inspectGraph(){const data=caseId==='bonk'?graph:bundle?.graph.data;if(!data)return;const queries=data.queries;const body=root.querySelector('#walkthrough-evidence')!;++sourceRequest;body.innerHTML=`<h3>Dependency graph queries</h3><p class="walkthrough-basis">${esc(data.source==='neo4j'?'NEO4J AURA':'LOCAL FALLBACK')}</p><p>${esc(data.host??'No remote host')}${data.reason?' · '+esc(data.reason):''}</p>${queries.map(q=>`<details><summary>${esc(q.title)} · ${q.rows.length} rows</summary><pre>${esc(q.cypher)}</pre><pre>${esc(JSON.stringify(q.rows.slice(0,8),null,2))}</pre><p>First ${Math.min(8,q.rows.length)} rows shown. The full query response is in the API.</p></details>`).join('')}<p class="walkthrough-muted">The presentation diagram summarizes captured dependencies. The query source above identifies whether database retrieval succeeded.</p>`;}
root.addEventListener('click',e=>{const t=(e.target as Element).closest<HTMLElement>('button,a');if(!t)return;
 if(t.hasAttribute('data-walkthrough-exit')){e.preventDefault();location.href=t.getAttribute('href')!;}
 else if(t.dataset.walkthroughCase)location.hash='walkthrough-'+t.dataset.walkthroughCase;
 else if(t.dataset.walkthroughScene){scene=Number(t.dataset.walkthroughScene);++sourceRequest;render();}
 else if(t.hasAttribute('data-walkthrough-next')){if(scene<3){scene++;render();}else location.hash=caseId==='bonk'?'walkthrough-mnde':'walkthrough-bonk';}
 else if(t.hasAttribute('data-walkthrough-previous')){scene=Math.max(0,scene-1);render();}
 else if(t.hasAttribute('data-walkthrough-reload'))void load(true);
 else if(t.dataset.walkthroughFact){const f=currentFacts()[Number(t.dataset.walkthroughFact)];if(f)void inspect(f);}
 else if(t.dataset.walkthroughLink)inspectLink(t.dataset.walkthroughLink);
 else if(t.dataset.walkthroughReceipt&&packet){const r=packet.observed.receipts.find(r=>r.txIndex===Number(t.dataset.walkthroughReceipt));if(r)void inspect({label:`Transaction ${r.txIndex+1} receipt`,text:`${r.success?'Successful':'Failed'} receipt ${r.signature}; ${date(r.blockTime?new Date(r.blockTime*1000).toISOString():null)}. Success alone does not decode unsupported instructions.`,basis:'observed',ids:r.evidenceIds,slot:r.slot});}
 else if(t.dataset.walkthroughQuestion)ask(t.dataset.walkthroughQuestion);
 else if(t.dataset.walkthroughChatCite){const [i,j]=t.dataset.walkthroughChatCite.split(':').map(Number);const f=messages[i!]?.facts[j!];if(f)void inspect(f);}
 else if(t.hasAttribute('data-walkthrough-graph'))inspectGraph();
});
document.addEventListener('keydown',e=>{if(root.hidden||(e.target as HTMLElement).matches('input,textarea,button,a,summary'))return;if(e.key==='ArrowRight')root.querySelector<HTMLButtonElement>('[data-walkthrough-next]')?.click();if(e.key==='ArrowLeft')root.querySelector<HTMLButtonElement>('[data-walkthrough-previous]')?.click();});
async function load(force=false){const id=caseId,n=++request;error='';++sourceRequest;render();try{if(id==='bonk'){if(force||!packet){const results=await Promise.all([fetchJson<Packet>('/api/cases/bonk-bip76/export/packet.json'),fetchJson<View>('/api/cases/bonk-bip76'),fetchJson<GraphAnswer>('/api/graph')]);if(n!==request)return;[packet,view,graph]=results;bonkStory(packet);}}else if(force||!bundle){const result=await fetchJson<BundleResponse>('/api/tokenomics/marinade');if(n!==request)return;bundle=result;}}catch(e){if(n!==request)return;error=(e as Error).message;}if(n===request)render();}
function route(){const hash=location.hash.slice(1);const active=hash==='walkthrough-bonk'||hash==='walkthrough-mnde';root.hidden=!active;launcher.hidden=active;document.body.classList.toggle('case-walkthrough-mode',active);const shell=document.querySelector<HTMLElement>('.shell');if(shell)shell.inert=active;if(!active){++request;++sourceRequest;return;}caseId=hash==='walkthrough-bonk'?'bonk':'mnde';scene=0;messages=[];selectedFact=null;void load();}
window.addEventListener('hashchange',route);route();
