import type { GovernanceBridge } from './graph-overview';
import { graphBadge, refreshGraphOverview, governanceBridgeCard } from './graph-overview-view';
import type { BundleResponse, SectionId, EvidenceResponse, PathLink } from '../tokenomics/api';
import { escape, title, amount, provenance, status, renderSection, graphPicture, short } from './tokenomics-view';
import { answerQuestion, type QuestionAnswer } from './tokenomics-questions';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const tabs: [SectionId|'overview',string][]=[['overview','Answer & path'],['control','Control'],['parameters','Parameters'],['programs','Programs'],['participation','Participation'],['holders','Holders & float'],['flows','Flows'],['claims','Claims vs chain'],['graph','Graph']];
type Message={role:'user'|'assistant';text:string;answer?:QuestionAnswer;at?:string};
export class TokenomicsWorkspace {
  private bridge?: GovernanceBridge; private bridgeError = ''; private bridgeRequest = 0;
  active=false; bundle:BundleResponse|null=null; tab:SectionId|'overview'='overview'; private request=0; private pathMode='route'; private graphType='all'; private graphSearch=''; private messages:Message[]=[]; private busy=false; private evidenceRequest=0;
  constructor(private onOpen:()=>void,private onNotice:(text:string)=>void){
    document.addEventListener('click',e=>{const t=(e.target as Element).closest<HTMLElement>('[data-tg-open],[data-tg-tab],[data-tg-link],[data-tg-node],[data-tg-entity],[data-tg-evidence],[data-tg-action],[data-tg-question],[data-tg-panel],[data-tg-pathmode]');if(!t)return;
      if(t.hasAttribute('data-tg-open'))void this.open();else if(!this.active)return;
      else if(t.dataset.tgPathmode){this.pathMode=t.dataset.tgPathmode;this.render();}
      else if(t.dataset.tgTab)this.setTab(t.dataset.tgTab as SectionId|'overview');
      else if(t.dataset.tgLink)this.inspectLink(t.dataset.tgLink);
      else if(t.dataset.tgNode)this.inspectNode(t.dataset.tgNode);
      else if(t.dataset.tgEntity)this.inspectEntity(t.dataset.tgEntity);
      else if(t.dataset.tgEvidence)void this.evidence(t.dataset.tgEvidence.split(','),t.dataset.tgLabel??'Supporting evidence');
      else if(t.dataset.tgQuestion)void this.ask(t.dataset.tgQuestion);
      else if(t.dataset.tgPanel)this.panel(t.dataset.tgPanel as 'chat'|'details');
      else if(t.dataset.tgAction==='workflow')this.details('How the research works','<p>Choose the protocol question → capture sources → decode mechanisms and controllers → connect the dependency graph → inspect findings → retrieve a cited answer.</p><h3>Documents</h3><p>Prepared documentation captures and registry claims retain their dates. Claims are checked against the supported chain records.</p><h3>Contract interfaces and state</h3><p>Recorded on-chain interfaces declare layouts and signer roles. Decoded account state identifies parameters and authorities; inferred instruction links remain inferred.</p><h3>Current captures and historical data</h3><p>Every value carries its capture date and slot. Historical receipts and observed flows carry their own time windows. Reloading this page does not refresh chain state.</p><h3>Graph and questions</h3><p>The API returns typed dependencies and graph query results. The question interface retrieves those records with evidence links; it is not a language model.</p>');
      else if(t.dataset.tgAction==='reload')void this.fetch();else if(t.dataset.tgAction==='graph-load')void this.loadGraph();else if(t.dataset.tgAction==='print')this.print();else if(t.dataset.tgAction==='close')$('#tg-inspector').classList.remove('open');else if(t.dataset.tgAction==='chat-open')this.panel('chat');
    });
    document.addEventListener('keydown',e=>{const t=e.target as HTMLElement;if(!this.active)return;if((e.key==='Enter'||e.key===' ')&&t.matches('g[data-tg-link],g[data-tg-node],g[data-tg-entity]')){e.preventDefault();t.dispatchEvent(new MouseEvent('click',{bubbles:true}));}if(e.key==='Escape')$('#tg-inspector').classList.remove('open');if(t.matches('[data-tg-tab]')&&['ArrowLeft','ArrowRight'].includes(e.key)){const all=[...document.querySelectorAll<HTMLButtonElement>('[role=tab][data-tg-tab]')];const n=all[(all.indexOf(t as HTMLButtonElement)+(e.key==='ArrowRight'?1:all.length-1))%all.length];const id=n.dataset.tgTab as SectionId|'overview';this.setTab(id);document.querySelector<HTMLButtonElement>(`[role=tab][data-tg-tab="${id}"]`)?.focus();}});
    document.addEventListener('change',e=>{const t=e.target as HTMLSelectElement;if(t.id==='tg-graph-type'){this.graphType=t.value;this.renderGraphPicture();}});
    document.addEventListener('input',e=>{const t=e.target as HTMLInputElement;if(t.id==='tg-graph-search'){this.graphSearch=t.value;this.renderGraphPicture();}});
    $('#tg-question-form').addEventListener('submit',e=>{e.preventDefault();void this.ask( $<HTMLTextAreaElement>("#tg-question-input").value);});
  }
  close(){this.active=false;++this.request;++this.evidenceRequest;document.body.classList.remove('tokenomics-mode');$('#tg-workspace').hidden=true;$('#tg-inspector').hidden=true;document.querySelector('[data-tg-open]')?.removeAttribute('aria-current');}
  async open(){this.active=true;void refreshGraphOverview();this.onOpen();document.body.classList.add('tokenomics-mode');$('#tg-workspace').hidden=false;$('#tg-inspector').hidden=false;document.querySelector('[data-tg-open]')?.setAttribute('aria-current','true');history.replaceState(null,'','/#tokenomics');$('#case-kind').textContent='Tokenomics dependency graph';this.panel('chat',false);if(this.bundle)this.render();else await this.fetch();if(this.tab==='graph')void this.fetchBridge();}
  private async get<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{...init,signal:AbortSignal.timeout(init?.method==='POST'?150_000:40_000)});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(response.status===404?'Tokenomics API is not installed in this frontend worktree yet. The backend integration is in progress.':data.error??`Request failed (${response.status})`);}return response.json();}
  async fetch(){const request=++this.request;$('#tg-reload').setAttribute('disabled','');$('#tg-connection').textContent='Retrieving latest stored research…';try{const b=await this.get<BundleResponse>('/api/tokenomics/marinade');if(!this.active||request!==this.request)return;for(const [key] of tabs)if(key!=='overview'&&!b[key])throw new Error(`API section missing: ${key}`);if(!b.answer||!b.path||!b.offsets)throw new Error('Incomplete tokenomics bundle');this.bundle=b;this.render();if(!this.messages.length){this.messages.push({role:'assistant',text:'Ask about a fee, control authority, value route or dependency. Answers retrieve the exact records and graph query results in this research bundle; each fact retains its evidence basis and capture date.'});this.renderChat();}}catch(e){if(!this.active||request!==this.request)return;$('#tg-connection').textContent='Research data unavailable';$('#tg-view').innerHTML=`<div class="tg-pending failed"><h2>Waiting for the research backend</h2><p>${escape((e as Error).message)}</p><button class="secondary" data-tg-action="reload">Retry connection</button></div>`;this.onNotice((e as Error).message);}finally{if(request===this.request)$('#tg-reload').removeAttribute('disabled');}}
  private render(){if(!this.bundle||!this.active)return;const b=this.bundle;$('#tg-question').textContent=b.answer.data?.question??'Is there an enforceable path from Marinade’s activity to MNDE holders, what offsets it, and who can change it?';const ready=Object.values(b).filter(s=>s.status==='ready');const dates=ready.map(s=>s.asOf).filter((s):s is string=>Boolean(s)).sort();const slots=ready.flatMap(s=>s.slotRange??[]);$('#tg-connection').textContent=`${ready.length}/${Object.keys(b).length} sections ready · captured mainnet evidence`;$('#tg-freshness').textContent=`Latest section captures ${dates[0]??'date unavailable'}${dates.at(-1)!==dates[0]?` — ${dates.at(-1)}`:''} · slots ${slots.length?`${Math.min(...slots)}–${Math.max(...slots)}`:'unavailable'}`;$('#tg-graph-badge').innerHTML=graphBadge();$('#tg-tabs').innerHTML=tabs.map(([id,label])=>`<button role="tab" data-tg-tab="${id}" aria-selected="${id===this.tab}" tabindex="${id===this.tab?0:-1}">${label}${id!=='overview'&&b[id].status!=='ready'?'<span class="tg-tab-pending" aria-label="in progress"> ·</span>':''}</button>`).join('');$('#tg-view').setAttribute('aria-label',tabs.find(([id])=>id===this.tab)?.[1]??this.tab);$('#tg-view').innerHTML=renderSection(b,this.tab,this.graphType,this.graphSearch,this.pathMode,governanceBridgeCard(this.bridge,this.bridgeError));}
  private setTab(tab:SectionId|'overview'){this.tab=['answer','path','offsets'].includes(tab)?'overview':tab;this.render();if(this.tab==='graph')void this.fetchBridge();}
  private async fetchBridge(){const request=++this.bridgeRequest;void refreshGraphOverview();try{const bridge=await this.get<GovernanceBridge>('/api/graph/governance-cases');if(request!==this.bridgeRequest)return;this.bridge=bridge;this.bridgeError='';}catch(e){if(request!==this.bridgeRequest)return;this.bridgeError=(e as Error).message;}if(this.active&&this.tab==='graph')this.render();}
  private panel(p:'chat'|'details',show=true){$('#tg-chat-panel').hidden=p!=='chat';$('#tg-details-panel').hidden=p!=='details';document.querySelectorAll('[data-tg-panel],[data-tg-pathmode]').forEach(t=>t.setAttribute('aria-pressed',String((t as HTMLElement).dataset.tgPanel===p)));if(show)$('#tg-inspector').classList.add('open');}
  private details(heading:string,body:string){++this.evidenceRequest;$('#tg-detail-title').textContent=heading;$('#tg-detail-content').innerHTML=body;this.panel('details');}
  private inspectLink(id:string){const l=this.bundle?.path.data?.links.find(l=>l.id===id);if(!l)return;const nodes=this.bundle!.path.data!.nodes;this.details(l.mechanism,`${status(l.status)}<p>${escape(nodes.find(n=>n.id===l.from)?.label??l.from)} → ${escape(nodes.find(n=>n.id===l.to)?.label??l.to)}</p><p>${escape(l.note)}</p>${provenance(l)}<h3>Parameters</h3>${l.parameters.map(p=>`<p>${escape(p.display)}</p>`).join('')||'<p>No parameter attached.</p>'}<h3>Observed flow</h3>${l.observed?`<strong>${escape(amount(l.observed.amount))}</strong><p>${l.observed.transactions} transactions<br>${l.observed.window.map(escape).join(' — ')}${l.observed.perDay?`<br>${escape(amount(l.observed.perDay))} per day`:''}</p>${provenance(l.observed)}`:'<p>No observed amount in this capture. This is not proof that no flow occurred.</p>'}<h3>Who controls it</h3>${l.controlledBy.map(id=>{const r=this.bundle!.control.data?.rows.find(r=>r.id===id),c=this.bundle!.control.data?.controllers.find(c=>c.id===id||c.id===r?.controllerId);return `<p>${escape(c?.label??r?.target??id)}${r?` · ${escape(r.role)}`:''}</p>`;}).join('')||'<p>Controller not resolved.</p>'}<h3>Linked claims</h3>${l.claims.map(id=>{const c=this.bundle!.claims.data?.rows.find(c=>c.id===id);return `<p>${escape(c?.chainResult??id)}</p>${c?`${status(c.status)}<small>${escape(c.text)}</small>`:''}`;}).join('')||'<p>No linked claims.</p>'}`);}
  private inspectNode(id:string){const n=this.bundle?.path.data?.nodes.find(n=>n.id===id);if(!n)return;const links=this.bundle!.path.data!.links.filter(l=>l.from===id||l.to===id);this.details(n.label,`<p>${escape(title(n.kind))}</p>${n.address?`<code>${escape(n.address)}</code>`:''}<h3>Connected mechanisms</h3>${links.map(l=>`<button class="tg-related" data-tg-link="${escape(l.id)}">${escape(l.mechanism)} ${status(l.status)}</button>`).join('')}`);}
  private inspectEntity(id:string){const g=this.bundle?.graph.data,n=g?.subgraph.nodes.find(n=>n.id===id);if(!g||!n)return;const edges=g.subgraph.edges.filter(e=>e.from===id||e.to===id);this.details(n.label,`<p>${escape(n.type)}</p><code>${escape(n.id)}</code><h3>Graph relationships</h3>${edges.map(e=>`<p>${escape(e.label||title(e.type))}<br><small>${escape(g.subgraph.nodes.find(n=>n.id===(e.from===id?e.to:e.from))?.label??'Related entity')} · ${escape(e.basis)}</small></p>`).join('')}<p class="tg-note">Source: ${escape(g.source)}. Open the related research section for the supporting source records.</p>`);}
  private renderGraphPicture(){const g=this.bundle?.graph.data;if(g&&$('#tg-graph-picture'))$('#tg-graph-picture').innerHTML=graphPicture(g,this.graphType,this.graphSearch,this.bundle??undefined);}
  async evidence(ids:string[],label:string){const request=++this.evidenceRequest;this.panel('details');$('#tg-detail-title').textContent=label;$('#tg-detail-content').innerHTML='<p class="tg-note">Retrieving source records…</p>';try{const batches=[];for(let i=0;i<ids.length;i+=200)batches.push(ids.slice(i,i+200));const result:EvidenceResponse={items:[],missing:[]};for(const batch of batches){const search=new URLSearchParams();batch.forEach(id=>search.append('id',id));const r=await this.get<EvidenceResponse>(`/api/tokenomics/marinade/evidence?${search}`);if(request!==this.evidenceRequest||!this.active)return;result.items.push(...r.items);result.missing.push(...r.missing);}$('#tg-detail-content').innerHTML=`${result.missing.length?`<p class="error">${result.missing.length} source records missing from this bundle.</p>`:''}${result.items.map(r=>`<article class="source-item"><strong>${escape(r.method)}</strong><p>${escape(r.source==='rpc'?'Live RPC capture':'Recorded mainnet fixture')} · ${escape(r.retrievedAt)}<br>Slot ${r.slot??'unavailable'}</p><code>${escape(r.id)}</code><details><summary>Read parameters and integrity</summary><pre>${escape(JSON.stringify(r.params,null,2))}</pre><p>SHA-256</p><code>${escape(r.responseSha256)}</code><p>${escape(r.fixture??'No local fixture path')}</p></details></article>`).join('')||'<p>No source records returned.</p>'}`;}catch(e){if(request===this.evidenceRequest)$('#tg-detail-content').innerHTML=`<p class="error">${escape((e as Error).message)}</p>`;}}
  private async loadGraph(){if(!this.bundle?.graph.data?.configured)return;const button=document.querySelector<HTMLButtonElement>('[data-tg-action=graph-load]');if(button){button.disabled=true;button.textContent='Loading Neo4j…';}try{await this.get('/api/tokenomics/marinade/graph/load',{method:'POST'});await this.fetch();await this.fetchBridge();this.onNotice('Graph index loaded. Source evidence capture dates are unchanged.');}catch(e){this.onNotice((e as Error).message);}finally{if(button){button.disabled=false;button.textContent='Load latest graph into Neo4j';}}}
  private async ask(question:string){question=question.trim().slice(0,600);if(!question||this.busy)return;this.panel('chat');this.messages.push({role:'user',text:question}); $<HTMLTextAreaElement>("#tg-question-input").value='';this.busy=true;this.renderChat();try{const b=await this.get<BundleResponse>('/api/tokenomics/marinade');if(!this.active)return;this.bundle=b;this.messages.push({role:'assistant',text:'',answer:answerQuestion(question,b),at:new Date().toISOString()});this.render();}catch(e){this.messages.push({role:'assistant',text:`Cannot retrieve research data: ${(e as Error).message}. No answer has been inferred from unavailable data.`});}finally{this.busy=false;this.renderChat();}}
  private renderChat(){const target=$('#tg-messages');target.innerHTML=this.messages.map(m=>`<article class="tg-message ${m.role}"><small>${m.role==='user'?'YOU':'LINCHPIN · EVIDENCE RETRIEVAL'}</small><p>${escape(m.answer?.text??m.text)}</p>${m.answer?`${m.answer.facts.map(f=>`<div class="tg-chat-fact"><p>${escape(f.text)}</p>${provenance(f,'Evidence')}</div>`).join('')}${m.answer.query?`<div class="tg-chat-fact"><strong>${escape(m.answer.query.title)}</strong><p>Graph source: ${escape(m.answer.query.source)}</p>${m.answer.query.rows.map(r=>`<p>${Object.entries(r).map(([k,v])=>`${escape(title(k))}: ${escape(v)}`).join('<br>')}</p>`).join('')||'<p>No matching rows.</p>'}</div>`:''}${m.answer.limitations.map(l=>`<p class="tg-note">In progress: ${escape(l)}</p>`).join('')}<div class="tg-chat-links">${m.answer.sections.map(s=>`<button data-tg-tab="${s==='answer'?'overview':s}">Open ${escape(title(s))} →</button>`).join('')}</div><small>Retrieved ${escape(m.at)} · capture dates shown with each fact. This did not refresh the chain.</small>`:''}</article>`).join('')+(this.busy?'<p class="tg-chat-working" role="status">Retrieving research bundle and graph results…</p>':'');$('#tg-question-submit').toggleAttribute('disabled',this.busy);target.scrollTop=target.scrollHeight;}
  private print(){if(!this.bundle)return;const oldTab=this.tab;this.tab='overview';this.render();window.print();this.tab=oldTab;this.render();}
}
