import type { BundleResponse, SectionId, SectionEnvelope, Provenance, Amount, Address, PathData, GraphData, Metric, LinkStatus } from '../tokenomics/api';
export const escape = (v: unknown): string => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const title = (v: string) => v.replaceAll('-', ' ').replaceAll('_', ' ').replace(/([a-z])([A-Z])/g,'$1 $2');
export const short = (v: string) => v.length > 21 ? `${v.slice(0,8)}…${v.slice(-5)}` : v;
export const amount = (v: Amount | null | undefined) => v ? `${v.display} ${v.unit}` : 'Not available';
export const parameterValue = (display:string,unit:string) => display.trim().endsWith(unit) ? display : `${display} ${unit}`;
export const address = (v: Address | null | undefined) => v ? `<span title="${escape(v.address)}">${escape(v.label ?? short(v.address))}</span>${v.label && v.labelBasis ? `<small>Label: ${escape(v.labelBasis)}</small>` : ''}` : 'Unresolved';
export const status = (v: string) => `<span class="tg-status ${escape(v)}">${escape(title(v))}</span>`;
export function provenance(p: Provenance, label = 'Inspect evidence') {
  const bases = Array.isArray(p.basis) ? p.basis : [p.basis];
  return `<div class="tg-provenance"><span>${escape(bases.join(' · '))}</span><span>Slot ${p.slot ?? 'unavailable'}</span>${p.asOf ? `<time>${escape(p.asOf)}</time>` : '<span>Date unavailable</span>'}${p.evidenceIds.length ? `<button class="source-button" data-tg-evidence="${escape(p.evidenceIds.join(','))}" data-tg-label="${escape(label)}">${escape(label)} ↗</button>` : '<span>No attached records</span>'}</div>`;
}
export function pending(e: SectionEnvelope<unknown>) {
  return `<div class="tg-pending ${e.status}"><strong>${e.status === 'failed' ? 'Section unavailable' : 'In progress'}</strong><p>${escape(e.error ?? (e.notes.join(' ') || 'This section has not been captured yet.'))}</p><small>${escape(e.title)}</small></div>`;
}
export function frame(e: SectionEnvelope<unknown>, body: () => string) {
  return e.status !== 'ready' || !e.data ? pending(e) : `${body()}${e.assumptions.length ? `<details class="tg-method"><summary>Assumptions and method</summary><ul>${e.assumptions.map(a=>`<li>${escape(a)}</li>`).join('')}</ul></details>` : ''}${e.notes.length ? `<p class="tg-note">${e.notes.map(escape).join(' ')}</p>` : ''}<p class="tg-section-date">Evidence captured ${escape(e.asOf ?? 'date unavailable')} · slots ${e.slotRange?.join('–') ?? 'unavailable'} · ${e.evidenceCount.toLocaleString()} records</p>`;
}
export const table = (headers: string[], rows: string[][]) => `<div class="tg-table-wrap"><table class="tg-table"><thead><tr>${headers.map(h=>`<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${rows.length ? '' : '<p class="tg-note">No rows in this captured section.</p>'}`;
export const metricRows = (metrics: Metric[]) => metrics.map(m=>`<div class="tg-metric"><div><span>${escape(m.label)}</span><strong>${escape(m.amount ? amount(m.amount) : m.value)}</strong>${m.note ? `<p>${escape(m.note)}</p>` : ''}</div>${provenance(m,m.label)}</div>`).join('');
const statusNames: LinkStatus[] = ['enforced-by-code','operated-by-accounts','claimed-only','not-observed','contradicted','pending'];
export function pathPicture(data: PathData, mode='all') {
  const governanceIds=new Set(data.nodes.filter(n=>n.kind==='governance'||/locking|voting|admin-authority|fee-parameters/.test(n.id)).map(n=>n.id));
  const treasuryId=data.nodes.find(n=>n.kind==='account'&&/treasury/i.test(n.label))?.id;
  let subset=data.nodes;
  if(mode==='governance') subset=data.nodes.filter(n=>governanceIds.has(n.id));
  else if(mode==='income') subset=data.nodes.filter(n=>n.kind==='activity'||n.kind==='fee'||n.id===treasuryId||/destination/.test(n.id));
  else if(mode==='route'&&treasuryId){
    const seen=new Set<string>();const order:string[]=[];
    const visit=(id:string)=>{if(seen.has(id))return;seen.add(id);order.push(id);for(const l of data.links.filter(l=>l.from===id))if(!governanceIds.has(l.to))visit(l.to);};visit(treasuryId);
    subset=order.flatMap(id=>data.nodes.find(n=>n.id===id)??[]);
  }
  const visible=new Set(subset.map(n=>n.id));data={nodes:subset,links:data.links.filter(l=>visible.has(l.from)&&visible.has(l.to))};
  if (!data.nodes.length) return '<p class="tg-note">No value path available in this section.</p>';
  // Layer along directed dependencies, retaining loops as curved return paths.
  const positions = new Map(data.nodes.map((n,i)=>[n.id,{x:35+(Math.floor(i/3)%2?2-i%3:i%3)*265,y:45+Math.floor(i/3)*150}]));
  const height = 70+Math.ceil(data.nodes.length/3)*150;
  const links = data.links.map((l,i)=>{
    const a=positions.get(l.from),b=positions.get(l.to); if(!a||!b) return '';
    const forward=b.x>a.x;const d = a.y===b.y ? `M${a.x+(forward?224:0)},${a.y+36} L${b.x+(forward?0:224)},${b.y+36}` : `M${a.x+112},${a.y+72} C${a.x+112},${a.y+110} ${b.x+112},${b.y-35} ${b.x+112},${b.y}`;
    const x=(a.x+b.x)/2+112, y=a.y===b.y ? a.y+102 : (a.y+b.y)/2+52;
    return `<g role="button" tabindex="0" data-tg-link="${escape(l.id)}" aria-label="Inspect ${escape(l.mechanism)}; ${escape(title(l.status))}"><path class="tg-hit" d="${d}"/><path class="tg-edge ${l.status}" d="${d}" marker-end="url(#tg-arrow)"/><rect x="${x-74}" y="${y-13}" width="148" height="20" rx="3" fill="#fcfcf9"/><text class="tg-edge-label" x="${x}" y="${y}" text-anchor="middle">${escape(l.mechanism.length>25?l.mechanism.slice(0,23)+'…':l.mechanism)}</text></g>`;
  }).join('');
  const nodes=data.nodes.map(n=>{const p=positions.get(n.id)!;return `<g role="button" tabindex="0" data-tg-node="${escape(n.id)}" aria-label="Inspect ${escape(n.label)}"><rect class="tg-node" x="${p.x}" y="${p.y}" width="224" height="72" rx="5"/><text class="tg-node-type" x="${p.x+14}" y="${p.y+19}">${escape(title(n.kind).toUpperCase())}</text><text class="tg-node-label" x="${p.x+14}" y="${p.y+42}">${escape(n.label.length>30?n.label.slice(0,28)+'…':n.label)}</text>${n.address ? `<text class="tg-node-address" x="${p.x+14}" y="${p.y+59}">${escape(short(n.address))}</text>` : ''}</g>`;}).join('');
  return `<figure class="tg-path"><svg viewBox="0 0 850 ${height}" aria-label="Marinade tokenomics dependency path"><defs><marker id="tg-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" stroke="#708577" fill="none"/></marker></defs>${links}${nodes}</svg><figcaption>${statusNames.map(s=>`<span class="tg-legend ${s}">${escape(title(s))}</span>`).join('')}</figcaption></figure><div class="tg-link-list">${data.links.map(l=>`<button data-tg-link="${escape(l.id)}"><span>${escape(l.mechanism)}</span>${status(l.status)}<small>${escape(Array.isArray(l.basis)?l.basis.join(' · '):l.basis)} · ${l.observed ? escape(amount(l.observed.amount)) : 'Flow amount not observed'}</small></button>`).join('')}</div>`;
}
export function graphPicture(g: GraphData, type = 'all', query = '') {
  const q=query.toLowerCase();
  const matched=g.subgraph.nodes.filter(n=>(type==='all'||n.type===type)&&(!q||`${n.label} ${n.id}`.toLowerCase().includes(q)));
  const nodes=matched.slice(0,36), ids=new Set(nodes.map(n=>n.id));
  const positions=new Map(nodes.map((n,i)=>[n.id,{x:25+(i%3)*267,y:30+Math.floor(i/3)*103}]));
  const edges=g.subgraph.edges.filter(e=>ids.has(e.from)&&ids.has(e.to));
  return `<p class="tg-note">Showing ${nodes.length} of ${matched.length} matching entities and ${edges.length} connecting relations. Filter to focus the picture; the query tables retain the full results.</p><svg class="tg-graph-svg" viewBox="0 0 850 ${Math.max(150,Math.ceil(nodes.length/3)*103+30)}" aria-label="Tokenomics graph entities"><defs><marker id="tg-index-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="#92a89a"/></marker></defs>${edges.map(e=>{const a=positions.get(e.from)!,b=positions.get(e.to)!;return `<path d="M${a.x+117},${a.y+60} Q${(a.x+b.x)/2+117},${(a.y+b.y)/2+90} ${b.x+117},${b.y}" fill="none" stroke="#aabdae" stroke-width="1" marker-end="url(#tg-index-arrow)"><title>${escape(e.type)} · ${escape(e.basis)}</title></path>`;}).join('')}${nodes.map(n=>{const p=positions.get(n.id)!;return `<g role="button" tabindex="0" data-tg-entity="${escape(n.id)}" aria-label="Inspect ${escape(n.label)}"><rect class="tg-node" x="${p.x}" y="${p.y}" width="235" height="61" rx="4"/><text class="tg-node-type" x="${p.x+12}" y="${p.y+18}">${escape(n.type)}</text><text class="tg-node-label" x="${p.x+12}" y="${p.y+40}">${escape(n.label.length>29?n.label.slice(0,27)+'…':n.label)}</text></g>`;}).join('')}</svg>`;
}
export function renderSection(bundle: BundleResponse, section: SectionId | 'overview', graphType='all', search='', pathMode='route'): string {
  if(section==='overview') {
    const a=bundle.answer;
    const answerPanel=frame({...a,assumptions:[],notes:[]},()=>`<div class="tg-answer-heading">${status(a.data!.shortAnswer.status)}<h2>${escape(a.data!.shortAnswer.text)}</h2></div>`);
    const findings=frame(a,()=>`<div class="tg-statements">${a.data!.statements.map(s=>`<article><p>${escape(s.text)}</p>${status(s.status)}${provenance(s,'Evidence')}</article>`).join('')}</div>${a.data!.unknowns.length?`<details class="tg-method"><summary>Unresolved questions · ${a.data!.unknowns.length}</summary>${a.data!.unknowns.map(u=>`<p>${escape(u.text)}</p>${provenance(u)}`).join('')}</details>`:''}`);
    const route=frame(bundle.path,()=>`<div class="tg-path-modes" role="group" aria-label="Value path focus">${[['route','Treasury → MNDE'],['income','Fees into treasury'],['governance','Who controls the route'],['all','Whole dependency path']].map(([id,label])=>`<button data-tg-pathmode="${id}" aria-pressed="${id===pathMode}">${label}</button>`).join('')}</div>${pathPicture(bundle.path.data!,pathMode)}`);
    return `<section class="tg-answer">${answerPanel}</section><section><div class="tg-section-heading"><span>01 / VALUE PATH</span><h2>How activity can reach MNDE holders</h2><p>Select a mechanism to inspect the rules, observed flows and controller.</p></div>${route}</section><details class="tg-method tg-findings-fold"><summary>Headline findings · ${a.data?.statements.length??'pending'} with evidence</summary>${findings}</details><section><div class="tg-section-heading"><span>02 / CONTROL</span><h2>Who can change the path</h2></div>${renderSection(bundle,'control')}</section><section><div class="tg-section-heading"><span>03 / OFFSETS</span><h2>What offsets it</h2></div>${renderSection(bundle,'offsets')}</section>`;
  }
  if(section==='answer') return renderSection(bundle,'overview');
  if(section==='path') return frame(bundle.path,()=>pathPicture(bundle.path.data!));
  if(section==='control') return frame(bundle.control,()=>{
    const c=bundle.control.data!;
    const groups=new Map<string,typeof c.controllers>();
    for(const controller of c.controllers){const key=controller.type==='dao-governance'||controller.type==='council-realm'?`${controller.type}:${controller.realm?.address??controller.label}`:['wallet','unresolved','program','none'].includes(controller.type)?controller.type:controller.id;groups.set(key,[...(groups.get(key)??[]),controller]);}
    return [...groups.values()].map(group=>{const first=group[0],ids=new Set(group.map(c=>c.id));const rows=c.rows.filter(r=>ids.has(r.controllerId));const heading=first.type==='wallet'?'Individual wallets':first.type==='unresolved'?'Unresolved authorities':first.type==='program'?'Program-controlled authorities':first.label;
    return `<details class="tg-controller"><summary><strong>${escape(heading)}</strong>${status(first.type)}<span class="tg-note">${rows.length} mapped controls</span></summary>${group.map(controller=>`<div class="tg-controller-record"><p><span title="${escape(controller.address??'')}">${escape(controller.label.startsWith('Wallet ')?short(controller.address??''):controller.label)}</span> · ${escape(controller.threshold??'')} ${escape(controller.note??'')}</p>${provenance(controller)}${controller.members?.length?`<details><summary>Multisig members · ${controller.members.length}</summary><ul>${controller.members.map(m=>`<li>${address(m)}</li>`).join('')}</ul></details>`:''}</div>`).join('')}${table(['Can change','Required instruction / role','Authority'],rows.map(r=>[`${escape(r.target)}<small>${escape(c.controllers.find(controller=>controller.id===r.controllerId)?.type==='none'?'Authority absent in captured state':r.canChange)}</small>${provenance(r)}`,`${r.instructions.map(escape).join(', ')||'No setter'}<small>${escape(r.role)}</small>`,address(r.holder)]))}</details>`;}).join('');
  });
  if(section==='offsets') return frame(bundle.offsets,()=>bundle.offsets.data!.rows.map(r=>`<article class="tg-offset"><h3>${escape(r.label)}</h3><strong>${escape(amount(r.amount))}</strong><p>${escape(r.note)}</p>${r.window ? `<small>Window ${r.window.map(escape).join(' — ')}</small>` : ''}${provenance(r)}</article>`).join(''));
  if(section==='parameters') return frame(bundle.parameters,()=>table(['Economic parameter','Decoded value','Change instruction → authority'],bundle.parameters.data!.rows.map(r=>[`${escape(r.label)}<small>${escape(r.program)} · ${escape(r.field)}</small>`,`${escape(parameterValue(r.display,r.unit))}${provenance(r,r.label)}`,r.setBy.map(s=>`${escape(s.instruction)} → ${escape(s.role)}<small>${address(s.holder)} · ${escape(s.basis)}</small>`).join('<hr>') || 'Setter not mapped'])));
  if(section==='programs') return frame(bundle.programs,()=>table(['Program / interface','Upgrade controller','Activity / deployments'],bundle.programs.data!.rows.map(r=>[`${escape(r.idl?.name ?? short(r.address))}<small title="${escape(r.address)}">${escape(short(r.address))}${r.idl?` · ${escape(r.idl.version)} · ${r.idl.instructions} instructions`:''}</small>${provenance(r)}`,`${r.upgradeable?'Upgradeable':'Not upgradeable'}<small>${address(r.upgradeAuthority)}</small>`,`${escape(r.activity.newest ?? 'Activity date unavailable')}<small>${r.activity.txPerDay ?? 'Unknown'} transactions/day · ${r.activity.dormant===null?'Dormancy not established':r.activity.dormant?'Dormant in sampled window':'Activity observed'}</small><details><summary>Upgrade history</summary>${r.upgrades.map(u=>`<p>${escape(u.time ?? 'Date unavailable')} · slot ${u.slot ?? 'unknown'}<br><code>${escape(short(u.signature))}</code></p>`).join('') || '<p>No deployment history in this section.</p>'}</details>`])));
  if(section==='participation') return frame(bundle.participation,()=>`<h2>MNDE locking</h2>${metricRows(bundle.participation.data!.locking)}<h2>Voting power</h2>${metricRows(bundle.participation.data!.votingPower)}<h2>Top lockers</h2>${table(['Rank','Authority','Locked amount'],bundle.participation.data!.topLockers.map(r=>[escape(r.rank),address(r.authority),`${escape(amount(r.amount))}${provenance(r)}`]))}<h2>Program participation</h2>${metricRows(bundle.participation.data!.programs)}`);
  if(section==='holders') return frame(bundle.holders,()=>{const h=bundle.holders.data!;return `<h2>MNDE holders and float</h2>${metricRows(h.mnde.metrics)}${metricRows(h.mnde.float)}${table(['Rank','Owner / role','MNDE amount'],h.mnde.top.map(r=>[escape(r.rank),`${address(r.owner)}<small>${escape(r.role)}</small>`,`${escape(amount(r.amount))}${provenance(r)}`]))}<h2>mSOL holders and dependencies</h2>${metricRows(h.msol.metrics)}${table(['Rank','Owner / label','mSOL amount'],h.msol.top.map(r=>[escape(r.rank),`${address(r.owner)}<small>${escape(r.label)} · ${escape(r.program)}</small>`,`${escape(amount(r.amount))}${provenance(r)}`]))}${table(['Downstream entity','Amount','Accounts'],h.msol.downstream.map(r=>[`${escape(r.label ?? r.entity)}${provenance(r)}`,escape(amount(r.amount)),escape(r.accounts)]))}`;});
  if(section==='flows') return frame(bundle.flows,()=>{const f=bundle.flows.data!;return `<h2>Declared routes</h2>${table(['Instruction','Receiving account','Basis'],f.declaredRoutes.map(r=>[`${escape(r.program)}<small>${escape(r.instruction)}</small>`,`${escape(r.account)}<small>${escape(r.address)}<br>${escape(r.note)}</small>`,provenance(r)]))}<h2>Observed treasury flows</h2>${f.treasury.inflows ? `<p>${escape(amount(f.treasury.inflows.amount))} across ${f.treasury.inflows.transactions} transactions · ${f.treasury.inflows.window.map(escape).join(' — ')}</p>${provenance(f.treasury.inflows)}` : '<p class="tg-note">Treasury inflow window not available.</p>'}${table(['Historical date','Destination','Outflow'],f.treasury.outflows.map(r=>[escape(r.time),address(r.to),`${escape(amount(r.amount))}${provenance(r)}`]))}<h2>Buybacks by month</h2>${table(['Month','MNDE bought','Cost','MNDE sent / recipients'],f.buybacks.months.map(r=>[escape(r.month),`${escape(amount(r.mndeBought))}${provenance(r)}`,r.cost.map(c=>escape(amount(c))).join('<br>'),`${escape(amount(r.mndeSent))}<small>${r.recipients} recipients · share to lockers ${r.shareToLockers ?? 'unknown'}</small>`]))}`;});
  if(section==='claims') return frame(bundle.claims,()=>table(['Chain result first','Documentation claim','Status / basis'],bundle.claims.data!.rows.map(r=>[`${escape(r.chainResult)}<small>${escape(r.note)}</small>`,`${escape(r.text)}<small>${escape(r.source)}</small>`,`${status(r.status)}${provenance(r)}`])));
  return frame(bundle.graph,()=>{const g=bundle.graph.data!;return `<div class="tg-graph-source">${status(g.source==='neo4j'?'Neo4j connected':'Local graph fallback')}<span>${escape(g.host ?? g.reason ?? 'Rebuildable graph index')}</span><button class="secondary" data-tg-action="graph-load" ${g.configured?'':'disabled'}>Load latest graph into Neo4j</button></div><p class="tg-note">Graph query time does not change the capture date of its source evidence.</p><div class="tg-graph-filters"><label>Entity type <select id="tg-graph-type"><option value="all">All types</option>${[...new Set(g.subgraph.nodes.map(n=>n.type))].sort().map(t=>`<option value="${escape(t)}" ${t===graphType?'selected':''}>${escape(t)}</option>`).join('')}</select></label><label>Find entity <input type="search" id="tg-graph-search" placeholder="Name or address" value="${escape(search)}"></label></div><div id="tg-graph-picture">${graphPicture(g,graphType,search)}</div>${g.queries.map(q=>`<article class="tg-query"><h3>${escape(q.title)}</h3><p>${escape(q.question)}</p>${table(q.columns,q.rows.map(r=>q.columns.map(c=>escape(r[c] ?? 'Unavailable'))))}<details><summary>Query and parameters</summary><pre>${escape(q.cypher)}</pre><pre>${escape(JSON.stringify(q.params,null,2))}</pre></details></article>`).join('')}`;});
}
